disabled_rules: 
  - trailing_whitespace
  - line_length
  - multiple_closures_with_trailing_closure
  - empty_enum_arguments
  - force_cast
  - discarded_notification_center_observer
  - nesting
excluded: 
  - Pods